[package]
name = "easy-proxy"
version = "2.3.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dialoguer = "0.12"
dirs = "5"
hex = "0.4"
libc = "0.2"
rand = "0.8"
regex = "1"
rsa = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
signal-hook = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "time", "signal", "process", "sync"] }
unicode-width = "0.2"

[profile.release]
strip = true
opt-level = "z"
lto = true
